# Generated by Django 3.2.9 on 2021-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
