# Generated by Django 3.2.9 on 2021-11-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_writing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='writing',
            name='Title',
            field=models.TextField(),
        ),
    ]
