# Generated by Django 3.2.9 on 2021-11-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211108_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writing',
            new_name='Acedamic_Writing_Task1',
        ),
    ]
