# Generated by Django 3.2.9 on 2021-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_writing_acedamic_writing_task1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_General_Writing_Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Body', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='General_Writing_Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Body', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
