# Generated by Django 3.2.9 on 2021-11-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_academic_general_writing_task2_general_writing_task1'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_general_writing_task2',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='general_writing_task1',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
